Update psalm-baseline.xml
Command and output:
```
$ vendor/bin/psalm.phar --update-baseline=psalm-baseline.xml
Scanning files...
Analyzing files...

░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░  60 / 342 (17%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 120 / 342 (35%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 180 / 342 (52%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 240 / 342 (70%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 300 / 342 (87%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
------------------------------
3 errors fixed

ERROR: UndefinedClass - src/Propel/Generator/Platform/SqlitePlatform.php:56:20 - Class or interface SQLite3 does not exist (see https://psalm.dev/019)
        $version = SQLite3::version();

------------------------------
1 errors found
------------------------------
1540 other issues found.
You can display them with --show-info=true
------------------------------
Psalm can automatically fix 76 of these issues.
Run Psalm again with
--alter --issues=InvalidNullableReturnType,InvalidReturnType,InvalidFalsableReturnType --dry-run
to see what it can fix.
------------------------------

Checks took 3.36 seconds and used 328.892MB of memory
Psalm was able to infer types for 93.0727% of the codebase
```

Note that the error about missing class SQLite3 is because I don't have
ext-sqlite3 installed. It's also missing from `composer.json`. The
`--update-baseline` command flag doesn't add any new errors, but only
removes/reorders. To add error-ignores, the `--set-baseline=<file>` flag
should be used.